/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformRouteImport } from './routes/_platform'
import { Route as PlatformIndexRouteImport } from './routes/_platform/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as PlatformCoursesIndexRouteImport } from './routes/_platform/courses/index'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as PlatformCoursesCourseTemplateIdRouteImport } from './routes/_platform/courses/$courseTemplateId'

const PlatformRoute = PlatformRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformCoursesIndexRoute = PlatformCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => PlatformRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformCoursesCourseTemplateIdRoute =
  PlatformCoursesCourseTemplateIdRouteImport.update({
    id: '/courses/$courseTemplateId',
    path: '/courses/$courseTemplateId',
    getParentRoute: () => PlatformRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PlatformIndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/courses/$courseTemplateId': typeof PlatformCoursesCourseTemplateIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/courses/': typeof PlatformCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof PlatformIndexRoute
  '/courses/$courseTemplateId': typeof PlatformCoursesCourseTemplateIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/courses': typeof PlatformCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_platform': typeof PlatformRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_platform/': typeof PlatformIndexRoute
  '/_platform/courses/$courseTemplateId': typeof PlatformCoursesCourseTemplateIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/_platform/courses/': typeof PlatformCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/courses/$courseTemplateId'
    | '/api/auth/callback'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/login'
    | '/'
    | '/courses/$courseTemplateId'
    | '/api/auth/callback'
    | '/courses'
  id:
    | '__root__'
    | '/_platform'
    | '/auth/login'
    | '/_platform/'
    | '/_platform/courses/$courseTemplateId'
    | '/api/auth/callback'
    | '/_platform/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PlatformRoute: typeof PlatformRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/': {
      id: '/_platform/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/courses/': {
      id: '/_platform/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof PlatformCoursesIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/courses/$courseTemplateId': {
      id: '/_platform/courses/$courseTemplateId'
      path: '/courses/$courseTemplateId'
      fullPath: '/courses/$courseTemplateId'
      preLoaderRoute: typeof PlatformCoursesCourseTemplateIdRouteImport
      parentRoute: typeof PlatformRoute
    }
  }
}

interface PlatformRouteChildren {
  PlatformIndexRoute: typeof PlatformIndexRoute
  PlatformCoursesCourseTemplateIdRoute: typeof PlatformCoursesCourseTemplateIdRoute
  PlatformCoursesIndexRoute: typeof PlatformCoursesIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformIndexRoute: PlatformIndexRoute,
  PlatformCoursesCourseTemplateIdRoute: PlatformCoursesCourseTemplateIdRoute,
  PlatformCoursesIndexRoute: PlatformCoursesIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PlatformRoute: PlatformRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
