/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformRouteImport } from './routes/_platform'
import { Route as PlatformIndexRouteImport } from './routes/_platform/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as PlatformUserRouteImport } from './routes/_platform/user'
import { Route as PlatformRoadmapRouteImport } from './routes/_platform/roadmap'
import { Route as PlatformCoursesIndexRouteImport } from './routes/_platform/courses/index'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as PlatformUserUsernameRouteImport } from './routes/_platform/user/$username'
import { Route as PlatformCoursesCourseTemplateIdRouteImport } from './routes/_platform/courses/$courseTemplateId'
import { Route as PlaygroundCoursesCourseTemplateIdLessonsLessonTemplateIdRouteImport } from './routes/_playground/courses/$courseTemplateId/lessons/$lessonTemplateId'

const PlatformRoute = PlatformRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformUserRoute = PlatformUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformRoadmapRoute = PlatformRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformCoursesIndexRoute = PlatformCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => PlatformRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformUserUsernameRoute = PlatformUserUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => PlatformUserRoute,
} as any)
const PlatformCoursesCourseTemplateIdRoute =
  PlatformCoursesCourseTemplateIdRouteImport.update({
    id: '/courses/$courseTemplateId',
    path: '/courses/$courseTemplateId',
    getParentRoute: () => PlatformRoute,
  } as any)
const PlaygroundCoursesCourseTemplateIdLessonsLessonTemplateIdRoute =
  PlaygroundCoursesCourseTemplateIdLessonsLessonTemplateIdRouteImport.update({
    id: '/_playground/courses/$courseTemplateId/lessons/$lessonTemplateId',
    path: '/courses/$courseTemplateId/lessons/$lessonTemplateId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PlatformIndexRoute
  '/roadmap': typeof PlatformRoadmapRoute
  '/user': typeof PlatformUserRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/courses/$courseTemplateId': typeof PlatformCoursesCourseTemplateIdRoute
  '/user/$username': typeof PlatformUserUsernameRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/courses/': typeof PlatformCoursesIndexRoute
  '/courses/$courseTemplateId/lessons/$lessonTemplateId': typeof PlaygroundCoursesCourseTemplateIdLessonsLessonTemplateIdRoute
}
export interface FileRoutesByTo {
  '/roadmap': typeof PlatformRoadmapRoute
  '/user': typeof PlatformUserRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/': typeof PlatformIndexRoute
  '/courses/$courseTemplateId': typeof PlatformCoursesCourseTemplateIdRoute
  '/user/$username': typeof PlatformUserUsernameRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/courses': typeof PlatformCoursesIndexRoute
  '/courses/$courseTemplateId/lessons/$lessonTemplateId': typeof PlaygroundCoursesCourseTemplateIdLessonsLessonTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_platform': typeof PlatformRouteWithChildren
  '/_platform/roadmap': typeof PlatformRoadmapRoute
  '/_platform/user': typeof PlatformUserRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_platform/': typeof PlatformIndexRoute
  '/_platform/courses/$courseTemplateId': typeof PlatformCoursesCourseTemplateIdRoute
  '/_platform/user/$username': typeof PlatformUserUsernameRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/_platform/courses/': typeof PlatformCoursesIndexRoute
  '/_playground/courses/$courseTemplateId/lessons/$lessonTemplateId': typeof PlaygroundCoursesCourseTemplateIdLessonsLessonTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/roadmap'
    | '/user'
    | '/auth/login'
    | '/courses/$courseTemplateId'
    | '/user/$username'
    | '/api/auth/callback'
    | '/courses/'
    | '/courses/$courseTemplateId/lessons/$lessonTemplateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/roadmap'
    | '/user'
    | '/auth/login'
    | '/'
    | '/courses/$courseTemplateId'
    | '/user/$username'
    | '/api/auth/callback'
    | '/courses'
    | '/courses/$courseTemplateId/lessons/$lessonTemplateId'
  id:
    | '__root__'
    | '/_platform'
    | '/_platform/roadmap'
    | '/_platform/user'
    | '/auth/login'
    | '/_platform/'
    | '/_platform/courses/$courseTemplateId'
    | '/_platform/user/$username'
    | '/api/auth/callback'
    | '/_platform/courses/'
    | '/_playground/courses/$courseTemplateId/lessons/$lessonTemplateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PlatformRoute: typeof PlatformRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  PlaygroundCoursesCourseTemplateIdLessonsLessonTemplateIdRoute: typeof PlaygroundCoursesCourseTemplateIdLessonsLessonTemplateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/': {
      id: '/_platform/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/user': {
      id: '/_platform/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof PlatformUserRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/roadmap': {
      id: '/_platform/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof PlatformRoadmapRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/courses/': {
      id: '/_platform/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof PlatformCoursesIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/user/$username': {
      id: '/_platform/user/$username'
      path: '/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof PlatformUserUsernameRouteImport
      parentRoute: typeof PlatformUserRoute
    }
    '/_platform/courses/$courseTemplateId': {
      id: '/_platform/courses/$courseTemplateId'
      path: '/courses/$courseTemplateId'
      fullPath: '/courses/$courseTemplateId'
      preLoaderRoute: typeof PlatformCoursesCourseTemplateIdRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_playground/courses/$courseTemplateId/lessons/$lessonTemplateId': {
      id: '/_playground/courses/$courseTemplateId/lessons/$lessonTemplateId'
      path: '/courses/$courseTemplateId/lessons/$lessonTemplateId'
      fullPath: '/courses/$courseTemplateId/lessons/$lessonTemplateId'
      preLoaderRoute: typeof PlaygroundCoursesCourseTemplateIdLessonsLessonTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlatformUserRouteChildren {
  PlatformUserUsernameRoute: typeof PlatformUserUsernameRoute
}

const PlatformUserRouteChildren: PlatformUserRouteChildren = {
  PlatformUserUsernameRoute: PlatformUserUsernameRoute,
}

const PlatformUserRouteWithChildren = PlatformUserRoute._addFileChildren(
  PlatformUserRouteChildren,
)

interface PlatformRouteChildren {
  PlatformRoadmapRoute: typeof PlatformRoadmapRoute
  PlatformUserRoute: typeof PlatformUserRouteWithChildren
  PlatformIndexRoute: typeof PlatformIndexRoute
  PlatformCoursesCourseTemplateIdRoute: typeof PlatformCoursesCourseTemplateIdRoute
  PlatformCoursesIndexRoute: typeof PlatformCoursesIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformRoadmapRoute: PlatformRoadmapRoute,
  PlatformUserRoute: PlatformUserRouteWithChildren,
  PlatformIndexRoute: PlatformIndexRoute,
  PlatformCoursesCourseTemplateIdRoute: PlatformCoursesCourseTemplateIdRoute,
  PlatformCoursesIndexRoute: PlatformCoursesIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PlatformRoute: PlatformRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  PlaygroundCoursesCourseTemplateIdLessonsLessonTemplateIdRoute:
    PlaygroundCoursesCourseTemplateIdLessonsLessonTemplateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
